version: '3.6'
services:
  admin:
    build: admin
    depends_on:
      - api
    networks:
      - frontend
    ports:
      - "8081:80"
  api:
    build: api
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "8080:8080"
  db:
    build: db
    environment:
      POSTGRES_DB: signage
      POSTGRES_PASSWORD: pwd
      POSTGRES_USER: signage
    networks:
      - backend
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data:rw
  pages:
    build: pages
    depends_on:
      - api
    networks:
      - display
    ports:
      - "80:80"

networks:
  backend:
  frontend:
  display:

volumes:
 db-data:
